### ISSUE TITLE
Output Keys

### ISSUE THREAD

**Issue by ryanmurf** [Burke-Lauenroth-Lab/Rsoilwat#4]
I tried to read in a project with missing output keys. It failed.

**Comment by dschlaep** [comment]
I tested the current Rsoilwat31 commit '6aacbc5' with a missing line of output, e.g., TEMP. The simulation run well, and the output structure was properly set up. The TEMP slot contained matrices of size [0, 0]. I conclude that this is no longer an issue. Thanks
